### ISSUE TITLE
mrt-store refactor - ingest store and access services

### ISSUE THREAD

**Issue by dloy** [CDLUC3/mrt-doc#1040]
### Changes
- inclusion of Jenkinsfile for multipart pipe handling used in refactor
- changes to support Dependabot recommendations
- upgrade of jars to S3 as currently running in other refactors
- change of master to main in github
- LOG_STORE
- Terry's docker environment upgrades

### inclusion of Jenkinsfile
See - https://github.com/CDLUC3/mrt-store/blob/java-refactor/Jenkinsfile

### changes to support Dependabot recommendations
See - https://github.com/CDLUC3/mrt-store/security/dependabot

### upgrade of jars to S3 as currently running in other refactors
- This references mrt-cloud jars - for these include mrt-cloud jar specifically.
- Upgrade to
~~~
        <dependency>
            <groupId>com.amazonaws</groupId>
            <artifactId>aws-java-sdk</artifactId>
            <version>1.12.190</version>
        </dependency>
~~~
Has some risk. A previous upgrade on this jar caused server hangs - attributed to memory handling issues.

### change of master to main in github
see:
- https://www.r-bloggers.com/2020/07/5-steps-to-change-github-default-branch-from-master-to-main/
- https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/changing-the-default-branch

### LOG_STORE
Use environment variable LOG_STORE to direct microservice logging. This allows dynamic logs which helps with docker

### Terry's docker environment upgrades
Request needed changes

**Comment by dloy** [comment]
A problem has surfaced testing store. The pre-refactor version uses:
~~~
       <dependency>
          <groupId>org.apache.zookeeper</groupId>
          <artifactId>zookeeper</artifactId>
          <version>3.4.5</version>
      </dependency>
~~~
There is a dependabot alert on this as:
Access control bypass in Apache ZooKeeper #4 - see https://github.com/CDLUC3/mrt-store/security/dependabot/4

Upgrading to 3.5.* has the error:
java.lang.NoClassDefFoundError: Could not initialize class org.apache.zookeeper.common.ClientX509Util

Upgrading to 3.6.* has the error:
org.slf4j.helpers.MessageFormatter.arrayFormat(Ljava/lang/String;[Ljava/lang/Object;)Ljava/lang/String;

Upgrading to 3.7.0 works.
I am a bit concerned the 3.7.0 version may have problems in other microservices using zookeeper that do work with 3.5.*. These are ingest and inv.

Will continue to explore the error caused by 3.5.* that works in ingest and inv.

**Comment by elopatin-uc3** [comment]
Thanks for the update @dloy .

**Comment by dloy** [comment]
## Capistrano refactor support storage servers
Need updates to Capistrano to support refactor install handling.
/apps/dpr2store/tools/deploy/deploy_semver.sh
needs to be made available using the release tag:
MERRITT_STORAGE_RELEASE

### Stage
These changes need to be available on:
uc3-mrtstore01x2-stg
uc3-mrtstore02x2-stg
uc3-mrtaccess01x2-stg
uc3-mrtaccess02x2-stg

### Prod
uc3-mrtstore05x2-prd
uc3-mrtstore06x2-prd
uc3-mrtaccess01x2-prd
uc3-mrtaccess02x2-prd

**Comment by dloy** [comment]
### slf4j-logj412 dependency problem
A pom.xml exclusion is required on store because an unsupported jar for slf4j-log4j12 is not found.  When this error occurs the zookeeper daemons for token load handling fail to startup.

Error:
~~~
SLF4J: The requested version 1.5.6 by your slf4j binding is not compatible with [1.6, 1.7]
SLF4J: See http://www.slf4j.org/codes.html#version_mismatch for further details.
~~~

Fix:
~~~
            <plugin>
              <artifactId>maven-war-plugin</artifactId>
              <version>3.3.2</version>
              <configuration>
                <packagingExcludes>WEB-INF/lib/slf4j-log4j12-1.5.6.jar,WEB-INF/lib/mrt-jena-2.0-SNAPSHOT.jar</packagingExcludes>
              </configuration>
            </plugin>
~~~

This is a difficule bug to track - use mvn dependency:tree to identify the specific slf4j-log4j12 causing this problem.
